version: "2"

services:
  app:
    image: golang:alpine
    restart: always
    container_name: Padevusplatvorm_go
    networks:
      - app-tier
    ports:
      - 8080:8080
    volumes:
      - .:/go/src/Padevusplatvorm-be
    working_dir: /go/src/Padevusplatvorm-be
    depends_on:
      - mariadb
    command: go run main.go
  mariadb:
    image: mariadb
    restart: always
    container_name: mariadb
    networks:
      - app-tier
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=Padevusplatvorm
    volumes: 
      - ./data/db:/var/lib/mysql

networks:
  app-tier:
    driver: bridge